os: linux
dist: focal
language: python

jobs:
    include:
        - stage: website
          language: python
          script:
              - make html

          deploy:
              strategy: git
              provider: pages
              cleanup: true
              #github_token: $TRAVIS_GH_PAGES_KEY
              local_dir: "_build/"
              on:
                  branch: master
