version: '{build}'

branches:
  only:
    - master
init:
  - git config --global core.autocrlf input
clone_script:
  - ps: git clone -q --recursive --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - ps: git checkout -qf $env:APPVEYOR_REPO_COMMIT
  - ps: git submodule update --init --recursive

image:
  - Ubuntu2004

environment:
  GH_TOKEN:
    secure: REnDH58USTAew9/H3E6HJwTpDGA0gQye45i/iKXr4Oy1tToIlconUw2GEpxt/87d

install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip
  - sudo pip3 install sphinx sphinx-rtd-theme recommonmark dateutil

build_script:
  - cd docs && make html

after_build:
  - cd .. && pwd
  # checkout github pages branch, built html files persist
  - git checkout gh-pages
  # removed most of previous built files
  - rm -Rf _* *.* config
  # move generated file to top-level folder
  - mv -fv docs/_build/html/* . && mv -fv docs/_build/html/.[a-zA-z]* .
  # remove any remainders
  - rm -Rf docs
  # prepare committing built html files
  - git config user.name "$(git log master -1 --format='%an')"
  - git config user.email "$(git log master -1 --format='%ae')"
  # commit&push html files to github pages branch
  - |
    PUSH_URL=$(git remote -v | tail -n1 | awk '{gsub("https://","",$2);print $2}'); \
    git add -A \
    && if git commit -m "Generated gh-pages for commit $(git log master -1 --pretty=oneline --abbrev-commit)"; \
          then git push https://ibressler:${GH_TOKEN}@${PUSH_URL} gh-pages; \
       fi;
  # cleanup AppVeyor history
  - |
    git checkout master \
    && git submodule update --init --recursive \
    && python3 config/ci/citools/appveyor_keep_builds.py 10 --verbose

notifications:
  - provider: Email
    to:
      - ci@ingobressler.net
    on_build_success: false

# vim: set ts=2 sw=2 sts=2 tw=0 et:
