version: '{build}'

branches:
  only:
    - master
init:
  - git config --global core.autocrlf input

image:
  - Ubuntu2004

environment:
  GH_TOKEN:
    secure: REnDH58USTAew9/H3E6HJwTpDGA0gQye45i/iKXr4Oy1tToIlconUw2GEpxt/87d

install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip
  - sudo pip3 install sphinx sphinx-rtd-theme recommonmark 

build_script:
  - cd docs && make html

after_build:
  - cd .. && pwd
  - git checkout gh-pages
  - mv -fv docs/_build/html/* .
  - rm -Rf docs
  - git config user.name "$(git log master -1 --format='%an')"
  - git config user.email "$(git log master -1 --format='%ae')"
  - |
    PUSH_URL=$(git remote -v | tail -n1 | awk '{gsub("https://","",$2);print $2}'); \
    git add -A \
    && git commit -m "Generated gh-pages for commit $(git log master -1 --pretty=oneline --abbrev-commit)" \
    && git push https://ibressler:${GH_TOKEN}@${PUSH_URL} gh-pages

notifications:
  - provider: Email
    to:
      - ci@ingobressler.net
    on_build_success: false

# vim: set ts=2 sw=2 sts=2 tw=0 et:
