version: '{build}'

branches:
  only:
    - master
init:
  - git config --global core.autocrlf input
clone_depth: 1

image:
  - Ubuntu2004

#environment:
#  GH_API:
#    secure: 4YhqXzROm8WOjGMaeLJZj5fQi/yEV+o3XqgSdnGsYORTeAfCNODt3kmuTaPvAsaM

install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip
  - sudo pip3 install sphinx sphinx-rtd-theme recommonmark 

build_script:
  - cd docs && make html

after_build:
  - git checkout gh-pages
  - mv -fv docs/_build/html/* .
  - rm -Rf docs
  - |
    git add -A \
    && git ci -m "Generated gh-pages for commit $(git log master -1 --pretty=oneline --abbrev-commit)" \
    && git push origin gh-pages

notifications:
  - provider: Email
    to:
      - ci@ingobressler.net
    on_build_success: false

# vim: set ts=2 sw=2 sts=2 tw=0 et:
